"""Compatibility facade for the original single-file framework module."""

from .app import App, Route, Router
from .constants import DEFAULT_CORS_ALLOW_ORIGIN, MAGIC_WS, STATUS_MESSAGES
from .http import Request, Response, parse_http_request, parse_query_string, send_http_response
from .metrics import AppMetrics, install_metrics
from .cache import Cache, SQLiteMemoryCache, install_cache
from .caches import GlobalCacheRule, ViewResponseCache, install_caches
from .security import ACLRule, SecurityDecision, SecurityPolicy, install_security
from .tasks import (
    TASK_CANCELLED,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_PENDING,
    TASK_REJECTED,
    TASK_RUNNING,
    TaskCancelledError,
    TaskClosedError,
    TaskContext,
    TaskError,
    TaskHandle,
    TaskManager,
    TaskRejectedError,
)
from .server import HTTPServer
from .proxyi import (
    BALANCING_BEST,
    BALANCING_CONSISTENT_HASH,
    BALANCING_FIRST_AVAILABLE,
    BALANCING_IP_HASH,
    BALANCING_LEAST_BYTES_IN,
    BALANCING_LEAST_BYTES_OUT,
    BALANCING_LEAST_CONNECTIONS,
    BALANCING_LEAST_REQUESTS,
    BALANCING_LEAST_RESPONSE_TIME,
    BALANCING_POWER_OF_TWO_CHOICES,
    BALANCING_RANDOM,
    BALANCING_ROUND_ROBIN,
    BALANCING_WEIGHTED_ROUND_ROBIN,
    ProxyI,
    ProxyMetricsBucket,
    ProxyRule,
    ProxyRouteBuilder,
    ProxyTarget,
    RunningStats,
    SUPPORTED_BALANCING_STRATEGIES,
    install_proxyi,
    normalize_balance_mode,
    normalize_target,
    proxyi,
)
from .ws import (
    B64_ALPHABET,
    WebSocketConnectionClosedError,
    WebSocketFrame,
    WebSocket,
    WebSocketReadError,
    WebSocketReadTimeoutError,
    WebSocketProtocolError,
    base64_encode,
    handshake_websocket,
    handshake_websocket_with_options,
    is_ws_request,
    make_ws_frame_bytes,
    parse_close_payload,
    read_ws_frame_raw,
    recv_exact,
    sha1,
)

__all__ = [
    "App",
    "HTTPServer",
    "Request",
    "Response",
    "ProxyI",
    "proxyi",
    "ProxyRule",
    "ProxyRouteBuilder",
    "ProxyTarget",
    "ProxyMetricsBucket",
    "RunningStats",
    "install_proxyi",
    "normalize_balance_mode",
    "normalize_target",
    "SUPPORTED_BALANCING_STRATEGIES",
    "BALANCING_ROUND_ROBIN",
    "BALANCING_WEIGHTED_ROUND_ROBIN",
    "BALANCING_RANDOM",
    "BALANCING_LEAST_CONNECTIONS",
    "BALANCING_LEAST_RESPONSE_TIME",
    "BALANCING_LEAST_REQUESTS",
    "BALANCING_LEAST_BYTES_IN",
    "BALANCING_LEAST_BYTES_OUT",
    "BALANCING_IP_HASH",
    "BALANCING_CONSISTENT_HASH",
    "BALANCING_FIRST_AVAILABLE",
    "BALANCING_POWER_OF_TWO_CHOICES",
    "BALANCING_BEST",
    "AppMetrics",
    "install_metrics",
    "Cache",
    "SQLiteMemoryCache",
    "install_cache",
    "GlobalCacheRule",
    "ViewResponseCache",
    "install_caches",
    "ACLRule",
    "SecurityDecision",
    "SecurityPolicy",
    "install_security",
    "TaskError",
    "TaskClosedError",
    "TaskCancelledError",
    "TaskRejectedError",
    "TaskContext",
    "TaskHandle",
    "TaskManager",
    "TASK_PENDING",
    "TASK_RUNNING",
    "TASK_COMPLETED",
    "TASK_FAILED",
    "TASK_CANCELLED",
    "TASK_REJECTED",
    "Route",
    "Router",
    "WebSocket",
    "WebSocketFrame",
    "WebSocketReadError",
    "WebSocketReadTimeoutError",
    "WebSocketConnectionClosedError",
    "WebSocketProtocolError",
    "DEFAULT_CORS_ALLOW_ORIGIN",
    "MAGIC_WS",
    "STATUS_MESSAGES",
    "B64_ALPHABET",
    "base64_encode",
    "handshake_websocket",
    "handshake_websocket_with_options",
    "is_ws_request",
    "make_ws_frame_bytes",
    "parse_close_payload",
    "parse_http_request",
    "parse_query_string",
    "read_ws_frame_raw",
    "recv_exact",
    "send_http_response",
    "sha1",
]
